# POSSIBLE MAP CONFIGURATION

lev_1_easy = [
    "xxxxxxxxxx",
    "xp   xx xx",
    "x     xxxx",
    "x       xx",
    "x      xxx",
    "x   x   xx",
    "x      xxx",
    "x  x    xx",
    "xx      ex",
    "xxxxxxxxxx"
]

lev_1_medium = [
    "xxxxxxxxxx",
    "xp   xx xx",
    "x   x xxxx",
    "xx x x xxx",
    "x      x x",
    "x xxx xx x",
    "x x x  x x",
    "x  x     x",
    "xx      ex",
    "xxxxxxxxxx"
]

lev_1_hard = [
    "xxxxxxxxxx",
    "xpxx xx xx",
    "x  x xxxxx",
    "x  x x x x",
    "xx  xxxxxx",
    "xxx    xxx",
    "xxxx  xxxx",
    "xxxx   xxx",
    "xxxxxx  ex",
    "xxxxxxxxxx"
]

lev_2_easy = [
    "xxxxxxxxxxxxxxxxxxxx",
    "xp xx             xx",
    "x               xxxx",
    "xx    xx         xxx",
    "x x               xx",
    "xx               xxx",
    "xx              xxxx",
    "xxx     xx        xx",
    "xx         x      xx",
    "xx              xxxx",
    "xx               xxx",
    "xxx             x xx",
    "xxx   xx          xx",
    "x         x     x xx",
    "xx      xxx     xxxx",
    "xxxxx   xx      xxxx",
    "xxx         x   xxxx",
    "xxx              xxx",
    "xxxxxxx           ex",
    "xxxxxxxxxxxxxxxxxxxx"
]

lev_2_medium = [
    "xxxxxxxxxxxxxxxxxxxx",
    "xp xx    xx   x xxxx",
    "x   xxxxxxx xx xxxxx",
    "xx    xx    xxx  xxx",
    "x x        xxxxx  xx",
    "xx          xxxx xxx",
    "xx        xxxxxxxxxx",
    "xxx     xx xx xx  xx",
    "xx         x      xx",
    "xxxxxxxxxx      xxxx",
    "xxxxxxxxxxxxx    xxx",
    "xxxxxxxxxxxxx   xxxx",
    "xxx   xx          xx",
    "xxxxxxxxx       x xx",
    "xxxxxxxxxx      xxxx",
    "xxxxx   xx      xxxx",
    "xxx   x  x  x x xxxx",
    "xxx              xxx",
    "xxxxxxx   x  x    ex",
    "xxxxxxxxxxxxxxxxxxxx"
]


lev_2_hard = [
    "xxxxxxxxxxxxxxxxxxxx",
    "xp xxxxxxxxxxxxxxxxx",
    "x   xxxxxxxx    xxxx",
    "xx    xxxxxxxxxxxxxx",
    "x x   xxxxxxxxxxxxxx",
    "xx   xxxxxxxxxxxxxxx",
    "xx    xxxxxxxxxxxxxx",
    "xxx     xxxxxxxxxxxx",
    "xx         x  xxxxxx",
    "xx              xxxx",
    "xxxxxxxxxxxxx    xxx",
    "xxxxxxxxxxxxx   xxxx",
    "xxx   xxxxxxx   xxxx",
    "xxxxxxxxxxx     xxxx",
    "xxxxxx  xxx     xxxx",
    "xxxxxx xxx   xxxxxxx",
    "xxxxxxx xxxx    xxxx",
    "xxxxxxxxxxx      xxx",
    "xxxxxxxxxxxxxxxx  ex",
    "xxxxxxxxxxxxxxxxxxxx"
]

lev_3_easy = [
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xp xx              xx     xxxx",
    "x                  x      xxxx",
    "xx                 xxx   xxxxx",
    "x x   xxx     xxxxx      xxxxx",
    "xx   xxxxx               xxxxx",
    "xx    x     xx         xxxxxxx",
    "xxxxxx      xxxx        xxxxxx",
    "xx xxxx    x  xxxx      xxxxxx",
    "xx              xx      xxxxxx",
    "xxxx             xx     xxxxxx",
    "xx              xxx       xxxx",
    "xxx   x                   xxxx",
    "xxxxx                     xxxx",
    "xx  x               x       xx",
    "xxx         x     x       xxxx",
    "xxxx  x x x               xxxx",
    "xx                        xxxx",
    "xxxx   x       x          xxxx",
    "xxxxx     x        x      xxxx",
    "xxxx         x            xxxx",
    "xxx      x        x       xxxx",
    "xx   xx                   xxxx",
    "xxx                      xxxxx",
    "xxx                       xxxx",
    "xxxxxx             xx    xxxxx",
    "xx                xxx    x  xx",
    "xxx  x  xx            xxxxxxxx",
    "xxxx              x         ex",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
]

lev_3_medium = [
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xp xx            xxxxx xx xxxx",
    "x                  xxxxx  xxxx",
    "xx         xxxx    xxx   xxxxx",
    "x x   xxx     xxxxx      xxxxx",
    "xx   xxx        xxxxxxxx xxxxx",
    "xx    x     xx         xxxxxxx",
    "xxxxxx      xxxx        xxxxxx",
    "xx xxxx    x  xxxx      xxxxxx",
    "xx              xx      xxxxxx",
    "xxxx             xx     xxxxxx",
    "xx              xxx       xxxx",
    "xxx   x          xxxx x x xxxx",
    "xxxxx    xxxx   x    xxx xxxxx",
    "xx  x     xxxx      x    xxxxx",
    "xxx         x     x       xxxx",
    "xxxx  x x x         xx    xxxx",
    "xx        xxx   xxx xx    xxxx",
    "xxxx   x    xx   x  x x   xxxx",
    "xxxxx     x        x      xxxx",
    "xxxx         x            xxxx",
    "xxx      x        x       xxxx",
    "xx   xx                   xxxx",
    "xxx      xx   xx xxxx    xxxxx",
    "xxx  xxx       xx  x      xxxx",
    "xxxxxx             xx    xxxxx",
    "xx   x  x xxxx    xxx    x  xx",
    "xxx  x  xx            xxxxxxxx",
    "xxxx     xxxxxxxxxx         ex",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
]

lev_3_hard = [
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xp xxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "x   xxxxxxxx    xxxxxxxxxxxxxx",
    "xx    xxxxxxxxxxxxxxxxxxxxxxxx",
    "x x   xxxxxxxxxxxxxxxxxxxxxxxx",
    "xx   xxxxxxxxxxxxxxxxxxxxxxxxx",
    "xx    xxxxxxxxxxxxxxxxxxxxxxxx",
    "xxx     xxxxxxxxxxxxxxxxxxxxxx",
    "xx         x  xxxxxxxxxxxxxxxx",
    "xx              xxxxx xxxxxxxx",
    "xxxxxxxxxxxxx    xxxxxxxxxxxxx",
    "xxxxxxxxxxxxx   xxxxxxxxxxxxxx",
    "xxx   xxxxxxx    xxxxxxxxxxxxx",
    "xxxxxxxxxxx     xxxxxxxxxxxxxx",
    "xxxxxx  xxx     xxxxxxxxxxxxxx",
    "xxxxxx xxx      xxxxxxxxxxxxxx",
    "xxxx  x xxxx  x xxxxxxxxxxxxxx",
    "xxxxxxx xx     xxxxxxxxxxxxxxx",
    "xxxxxx    x xxxxxxxxxxxxxxxxxx",
    "xxxxxxxxx   xxxxxxxxxxxxxxxxxx",
    "xxxxxx      xxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxx     xxxxxxxxxxxxxxx",
    "xxxxxxxxxxx     xxxxxxxxxxxxxx",
    "xxxxxxxxxx   xxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxx       xx    xxxxxx",
    "xxxxxxxxxxxxxxx    xxxxxxxxxxx",
    "xxxxxxxxx xxxx    xxxxxxxx  xx",
    "xxxxxxxxxxxx          xxxxxxxx",
    "xxxxxxxxxx xxx    x         ex",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
]
